import type { Metadata } from "next";
import { Radley } from "next/font/google";
import "./globals.scss";

const radley = Radley({ subsets: ['latin'] , weight:"400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={radley.className}>{children}</body>
    </html>
  );
}
